config/routes.rb
Rails.application.routes.draw do
  resources :alunosprofs
  resources :professors
  resources :instrumentos
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instrumento.rb
class Instrumento < ApplicationRecord
    validates_presence_of :nome
    
    has_many :alunos
    has_many :professors
end

app/controllers/instrumentos_controller.rb
class InstrumentosController < ApplicationController
  before_action :set_instrumento, only: [:show, :edit, :update, :destroy]

  # GET /instrumentos
  # GET /instrumentos.json
  def index
    @instrumentos = Instrumento.all
  end

  # GET /instrumentos/1
  # GET /instrumentos/1.json
  def show
  end

  # GET /instrumentos/new
  def new
    @instrumento = Instrumento.new
  end

  # GET /instrumentos/1/edit
  def edit
  end

  # POST /instrumentos
  # POST /instrumentos.json
  def create
    @instrumento = Instrumento.new(instrumento_params)

    respond_to do |format|
      if @instrumento.save
        format.html { redirect_to @instrumento, notice: 'Instrumento was successfully created.' }
        format.json { render :show, status: :created, location: @instrumento }
      else
        format.html { render :new }
        format.json { render json: @instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instrumentos/1
  # PATCH/PUT /instrumentos/1.json
  def update
    respond_to do |format|
      if @instrumento.update(instrumento_params)
        format.html { redirect_to @instrumento, notice: 'Instrumento was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrumento }
      else
        format.html { render :edit }
        format.json { render json: @instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instrumentos/1
  # DELETE /instrumentos/1.json
  def destroy
    @instrumento.destroy
    respond_to do |format|
      format.html { redirect_to instrumentos_url, notice: 'Instrumento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrumento
      @instrumento = Instrumento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrumento_params
      params.require(:instrumento).permit(:nome, :familia)
    end
end

app/helpers/instrumentos_helper.rb
module InstrumentosHelper
end

app/views/instrumentos/_form.html.erb
<%= form_for(instrumento) do |f| %>
  <% if instrumento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instrumento.errors.count, "error") %> prohibited this instrumento from being saved:</h2>

      <ul>
      <% instrumento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :familia %>
    <%= f.text_field :familia %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instrumentos/edit.html.erb
<h1>Editing Instrumento</h1>

<%= render 'form', instrumento: @instrumento %>

<%= link_to 'Show', @instrumento %> |
<%= link_to 'Back', instrumentos_path %>

app/views/instrumentos/index.html.erb
<!doctype html>
<html lang="en">

<body>
    
    <p id="notice"><%= notice %></p>
    
<h1>Instrumentos</h1>

    <%= link_to "alunos", alunos_path %>
    <%= link_to "instrumentos", instrumentos_path %>
    <%= link_to "professors", professors_path %>

<table class="table table-hover table-dark"
  <thead>
    <tr>
      <th scope="row"></th>
      <th scope="col">Nome</th>
      <th scope="col">Familia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instrumentos.each do |instrumento| %>
      <tr>
        <th scope="row"></th>
        <td><%= instrumento.nome %></td>
        <td><%= instrumento.familia %></td>
        <td><%= link_to 'Show', instrumento %></td>
        <td><%= link_to 'Edit', edit_instrumento_path(instrumento) %></td>
        <td><%= link_to 'Destroy', instrumento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </body>
<br>

<p align="center"><%= link_to 'New Instrumento', new_instrumento_path %></p>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/instrumentos/new.html.erb
<h1>New Instrumento</h1>

<%= render 'form', instrumento: @instrumento %>

<%= link_to 'Back', instrumentos_path %>

app/views/instrumentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @instrumento.nome %>
</p>

<p>
  <strong>Familia:</strong>
  <%= @instrumento.familia %>
</p>

<%= link_to 'Edit', edit_instrumento_path(@instrumento) %> |
<%= link_to 'Back', instrumentos_path %>