config/routes.rb
Rails.application.routes.draw do
  resources :alunosprofs
  resources :professors
  resources :instrumentos
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alunosprof.rb
class Alunosprof < ApplicationRecord
    
    belongs_to :aluno
    belongs_to :professor
    
end

app/controllers/alunosprofs_controller.rb
class AlunosprofsController < ApplicationController
  before_action :set_alunosprof, only: [:show, :edit, :update, :destroy]

  # GET /alunosprofs
  # GET /alunosprofs.json
  def index
    @alunosprofs = Alunosprof.all
  end

  # GET /alunosprofs/1
  # GET /alunosprofs/1.json
  def show
  end

  # GET /alunosprofs/new
  def new
    @alunosprof = Alunosprof.new
  end

  # GET /alunosprofs/1/edit
  def edit
  end

  # POST /alunosprofs
  # POST /alunosprofs.json
  def create
    @alunosprof = Alunosprof.new(alunosprof_params)

    respond_to do |format|
      if @alunosprof.save
        format.html { redirect_to @alunosprof, notice: 'Alunosprof was successfully created.' }
        format.json { render :show, status: :created, location: @alunosprof }
      else
        format.html { render :new }
        format.json { render json: @alunosprof.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunosprofs/1
  # PATCH/PUT /alunosprofs/1.json
  def update
    respond_to do |format|
      if @alunosprof.update(alunosprof_params)
        format.html { redirect_to @alunosprof, notice: 'Alunosprof was successfully updated.' }
        format.json { render :show, status: :ok, location: @alunosprof }
      else
        format.html { render :edit }
        format.json { render json: @alunosprof.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunosprofs/1
  # DELETE /alunosprofs/1.json
  def destroy
    @alunosprof.destroy
    respond_to do |format|
      format.html { redirect_to alunosprofs_url, notice: 'Alunosprof was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alunosprof
      @alunosprof = Alunosprof.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alunosprof_params
      params.require(:alunosprof).permit(:aluno_id, :professor_id)
    end
end

app/helpers/alunosprofs_helper.rb
module AlunosprofsHelper
end

app/views/alunosprofs/_form.html.erb
<%= form_for(alunosprof) do |f| %>
  <% if alunosprof.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alunosprof.errors.count, "error") %> prohibited this alunosprof from being saved:</h2>

      <ul>
      <% alunosprof.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aluno_id %>
    <%= f.number_field :aluno_id %>
  </div>

  <div class="field">
    <%= f.label :professor_id %>
    <%= f.number_field :professor_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alunosprofs/edit.html.erb
<h1>Editing Alunosprof</h1>

<%= render 'form', alunosprof: @alunosprof %>

<%= link_to 'Show', @alunosprof %> |
<%= link_to 'Back', alunosprofs_path %>

app/views/alunosprofs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunosprofs</h1>

<table>
  <thead>
    <tr>
      <th>Aluno</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunosprofs.each do |alunosprof| %>
      <tr>
        <td><%= alunosprof.aluno.nome %></td>
        <td><%= alunosprof.professor.nome %></td>
        <td><%= link_to 'Show', alunosprof %></td>
        <td><%= link_to 'Edit', edit_alunosprof_path(alunosprof) %></td>
        <td><%= link_to 'Destroy', alunosprof, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alunosprof', new_alunosprof_path %>

app/views/alunosprofs/new.html.erb
<h1>New Alunosprof</h1>

<%= render 'form', alunosprof: @alunosprof %>

<%= link_to 'Back', alunosprofs_path %>

app/views/alunosprofs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aluno:</strong>
  <%= @alunosprof.aluno.nome %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @alunosprof.professor.nome %>
</p>

<%= link_to 'Edit', edit_alunosprof_path(@alunosprof) %> |
<%= link_to 'Back', alunosprofs_path %>