config/routes.rb
Rails.application.routes.draw do
  resources :alunosprofs
  resources :professors
  resources :instrumentos
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    validates_presence_of :nome
    validates_size_of :idade, minimum:2
    validates_presence_of :idade
    validates_numericality_of :idade
    
    belongs_to :instrumento
    has_many :professors, through: :alunosprofs
    has_many :alunosprofs
   
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :idade, :instrumento_id, :turno, :materia)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_form.html.erb
<%= form_for(aluno) do |f| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :idade %>
    <%= f.number_field :idade %>
  </div>

  <div class="field">
    <%= f.label :instrumento_id %>
    <%= f.number_field :instrumento_id %>
  </div>

  <div class="field">
    <%= f.label :turno %>
    <%= f.text_field :turno %>
  </div>

  <div class="field">
    <%= f.label :materia %>
    <%= f.text_field :materia %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<!doctype html>
<html lang="en">
<body>
  
    <p id="notice"><%= notice %></p>
    
    
    
<h1>Alunos</h1>

  <table align="center">
    <%= link_to "alunos", alunos_path %>
    <%= link_to "instrumentos", instrumentos_path %>
    <%= link_to "professors", professors_path %>
  </table>
  
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="row"></th>
      <th scope="col">id</th>
      <th scope="col">Nome</th>
      <th scope="col">Idade</th>
      <th scope="col">Instrumento</th>
      <th scope="col">Turno</th>
      <th scope="col">Materia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <th scope="row"></th>
        <td><%= aluno.id %></td>
        <td><%= aluno.nome %></td>
        <td><%= aluno.idade %></td>
        <td><%= aluno.instrumento.nome %></td>
        <td><%= aluno.turno %></td>
        <td><%= aluno.materia %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </body>
<br>

<p align="center"><%= link_to 'New Aluno', new_aluno_path %></p>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @aluno.idade %>
</p>

<p>
  <strong>Instrumento:</strong>
  <%= @aluno.instrumento.nome %>
</p>

<p>
  <strong>Turno:</strong>
  <%= @aluno.turno %>
</p>

<p>
  <strong>Materia:</strong>
  <%= @aluno.materia %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>